name = input("Podaj swoje imie: ")
print("Twoje imie to: {name}".format(name=name))
surname = input("Podaj swoje nazwisko: ")
print("Twoje imie to: {surname}".format(surname=surname))
birthDate = input("Podaj swoja date urodzenia: ")
print("Twoja data urodzenia to: {birthDate}".format(birthDate=birthDate))